### ISSUE TITLE
Having two or more players playing a Radiocast or Icecast related stream causes Volcano to crash

### ISSUE THREAD

**Issue by aarhuuus** [AmandaDiscord/Volcano#22] opened 2022-08-15 17:21 UTC
This has been discovered by playing two or more Radiocast or Icecast related stream, server has been allocated 2GB or memory via Docker container. 1 player sometimes causes Volcano to crash and sometimes it doesn't and would play music normally. Spawning another player would crash Volcano.

**Version used:** Volcano 1.1.6 with Node.JS 16 LTS (and 17)

Error Logs:
```js
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:1276:5)
    at new Frame (/home/container/node_modules/backtracker/dist/Frame.js:18:35)
    at Function.process (/home/container/node_modules/backtracker/dist/index.js:47:34)
    at Function.get stack [as stack] (/home/container/node_modules/backtracker/dist/index.js:27:28)
    at Object.getPrefix (file:///home/container/dist/util/Logger.js:39:35)
    at info (file:///home/container/dist/util/Logger.js:48:38)
    at Server.serverHandler (file:///home/container/dist/index.js:420:13)
    at runMicrotasks (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by PapiOphidian** [comment] 2022-08-15 17:28
BackTracker is causing some issues, so I will fix BackTracker and then see what the issue is regarding SHOUTCast and ICECast

**Comment by aarhuuus** [comment] 2022-08-15 17:47
It seems like this issue only affects SHOUTcast and ICEcast since YouTube streams work fine. Changing title...

**Comment by PapiOphidian** [comment] 2022-08-15 17:57
Can you give me tracks you tried to play

**Comment by aarhuuus** [comment] 2022-08-15 18:18
- https://s3.radio.co/sd43d6cc6d/listen
- https://s4.radio.co/s778110174/listen

These are foreign radio stations grabbed via the radio-browser API.

**Comment by PapiOphidian** [comment] 2022-08-15 18:24
These stations seem to work fine for me with no errors. The error stack you provided is coming from Volcano's Logger.error which isn't being called here
![image](https://user-images.githubusercontent.com/25259648/184693353-ebc4d3d2-f09d-481d-ba25-ee19835a768d.png)

**Comment by PapiOphidian** [comment] 2022-08-15 18:28
I've compiled a developer release you may try which includes the up to date package.json. You'd just have to npm install
[Volcano-1.1.7-dev-1.zip](https://github.com/AmandaDiscord/Volcano/files/9339080/Volcano-1.1.7-dev-1.zip)

**Comment by aarhuuus** [comment] 2022-08-15 18:36
It seems that this issue is fixed with the applied developer build but there's an error (but it doesn't really affect the performance of Volcano).

```bash
2022-08-15 18:33:04.252 ERROR 62 --- [      main] worker.js:481:12  : "Cannot create property 'audioPlayer' on boolean 'true'
TypeError: Cannot create property 'audioPlayer' on boolean 'true'
    at AudioPlayer.play (file:///home/container/node_modules/@discordjs/voice/dist/index.mjs:907:26)
    at Queue.play (file:///home/container/dist/worker.js:253:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
```

**Comment by PapiOphidian** [comment] 2022-08-15 18:40
Yup. I can see that error as well and working on it

**Comment by PapiOphidian** [comment] 2022-08-15 18:46
Looks like the 2nd URL is missing response headers and Volcano makes a fuss about that. Working on fixing

**Comment by PapiOphidian** [comment] 2022-08-15 19:29
Fixed in dev. Going to be publishing soon

**Closed as completed** 2022-08-15 20:15 UTC
