### ISSUE TITLE
FFmpeg not working

### ISSUE THREAD

**Issue by Tomato6966** [AmandaDiscord/Volcano#27] opened 2022-09-18 11:16 UTC
player.node.send({
 "op": "ffmpeg",
 "guildId": message.guildId,
 "args": ['aresample=48000,asetrate=48000*0.7,atempo=1.3,aresample=48000']
})
![image](https://user-images.githubusercontent.com/68145571/190899323-de844035-8b93-4240-ac90-7afcb8e922c4.png)

Audio just stucks.

Ubuntu 20

kernel: 5.19.5-051905-generic

node 18.9

ffmpeg-static and apt-get install ffmpeg both installed

**Comment by PapiOphidian** [comment] 2022-09-18 15:41
what source was being used?

**Comment by Tomato6966** [comment] 2022-09-23 12:43
the latest release

**Comment by PapiOphidian** [comment] 2022-09-23 12:43
I meant the track. Is it YouTube?

**Comment by PapiOphidian** [comment] 2022-09-24 01:03
This may or may not be fixed in 1.4.0
I wasn't able to reproduce the issue, but I've been using the development version internally. If it doesn't lmk

**Comment by PapiOphidian** [comment] 2022-09-27 23:15
If this hasn't been fixed, please provide more info, otherwise, this will be closed

**Comment by freegamerskids** [comment] 2022-10-11 15:36
this also happens to me, but it says: `(song) got stuck! Threshold surpassed: 10000`
![image](https://user-images.githubusercontent.com/60486718/195136138-35e848a9-c9f4-48f6-8b93-215d58ae8bc7.png)

**Comment by PapiOphidian** [comment] 2022-10-30 05:32
I have not been able to reproduce this issue. For testing purposes, I'd like to see if this has been fixed for you guys in 1.5.0

**Comment by freegamerskids** [comment] 2022-10-31 21:47
> I have not been able to reproduce this issue. For testing purposes, I'd like to see if this has been fixed for you guys in 1.5.0

This is still the issue. Haven't been fixed.

**Comment by PapiOphidian** [comment] 2022-11-02 01:52
I only now realized this was for op ffmpeg

**Comment by Peter-MJ-Parker** [comment] 2022-11-07 16:16
I wonder how many of these users were playing from heroku?? I personally don't use heroku as they share ip's between users and servers therefore complicating Discord rate limits and music bots.

**Comment by PapiOphidian** [comment] 2022-11-12 22:39
OP ffmpeg has now been removed as ffmpeg is planned to not be used in the future and because I cannot conceivably resolve these issues due to the arbitrary nature of the op. Should you be trying to use it to emulate the functionality of lavalink filter ops, please open an issue or a PR or message me on Discord an ffmpeg arg format to get similar results to lavalink's filter op. Should you REALLY desire ffmpeg, Volcano's plugin system allows you to mutate the ffmpeg args Array that Volcano passes to the streamPipeline of each and every source that has one.
https://github.com/AmandaDiscord/Volcano/blob/main/src/worker.ts#L129
This can be combined with the fact that plugins also have their own ws message handlers, but you will have to work around the fact that Volcano is threaded

**Closed as completed by PapiOphidian** 2022-11-12 22:39 UTC
